---

- name: Create a virtual machine from a template
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ cert_val }}"
    folder: "{{ vm_folder }}"
    name: "{{ inventory_hostname }}"
    state: "{{ vm_state }}"
    template: "{{ vm_template }}"
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    disk:
    - size_gb: "{{ vm_disk_size }}"
      datastore: "{{ vcenter_datastore }}"
    hardware:
      memory_mb: "{{ vm_memory }}"
      num_cpus: "{{ vm_cpus }}"
      num_cpu_cores_per_socket: "{{ vm_cores_cpu }}"
      scsi: "{{ vm_scsi }}"
      hotadd_cpu: "{{ vm_hotadd_cpu }}"
      hotadd_memory: "{{ vm_hotadd_mem }}"
#      version: "{{ vm_version }}"
      boot_firmware: "{{ vm_boot_firm }}"
    networks:
    - name: "{{ vm_network }}"
    wait_for_ip_address: yes
    customization:
      domain: "{{ guest_domain }}"
      dns_servers:
        - "{{ dns1 }}"
      dns_suffix:
        - "{{ guest_domain }}"
      hostname: "{{ inventory_hostname }}"
  delegate_to: localhost
  register: deploy

- name: Display VM info
  debug:
    var: deploy